services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_backup/ecommerce.sql:/docker-entrypoint-initdb.d/ecommerce.sql

  app:
    build: .
    container_name: ecommerce-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"

volumes:
  mysql_data: