apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace/namespace.yaml

  - mysql/secret.yaml
  - mysql/pvc.yaml
  - mysql/service.yaml
  - mysql/deployment.yaml

  - app/configmap.yaml
  - app/service.yaml
  - app/deployment.yaml