name: Ecommerce CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'ecommerce-ci4/**'

permissions:
  contents: write

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: ecommerce-app
  IMAGE_TAG: v${{ github.run_number }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./ecommerce-ci4

      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Kubernetes Manifest
        run: |
            sed -i "s|image: .*|image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG|g" kubernetes/app/deployment.yaml
      - name: Commit Manifest Changes
        run: |
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"

            git add kubernetes/app/deployment.yaml

            git commit -m "ci: update image tag to $IMAGE_TAG" || exit 0

            git push origin main